#!/bin/bash

echo "#!/bin/bash

set -eu

args=()

for arg in \"\$@\"; do
  case \"\$arg\" in
    -Bdynamic|-dynamic|-shared*|-symbolic|-nodefaultlibs|-nostartfiles) continue ;;
    *.so|*.so.*) echo \"Detected dynamic object: \$@\" > /tmp/log2.txt; exit 1;;
  esac

  args+=(\"\$arg\")
done

$1 \"\${args[@]}\"
"
