#!/bin/bash

for arg in "$@"; do
  case "$arg" in
    *.so.*)
      shared_lib=true
      break
    ;;
  esac
done

flags=()
if [ ! "${shared_lib:-}" ]; then
  flags+=("$TARGET_HOME/lib/crt1.o")
fi

echo "$@" >> /tmp/file

$CC $_CFLAGS "${flags[@]}" $STARTFILES "$@"
